services:
  mongodb:
    image: mongo
    container_name: mongo-database
    ports:
      - 27000:27017
    volumes:
      - mongovol:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8000:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongovol: {}